#!/bin/bash
#!/bin/zsh
#
# ====================================
# Author: Eunchong Kim
# Date: Aug., 2020
# Project: user-settings
# Description: git aliases
# ====================================


# ------------------------------------
#               Basic
# ------------------------------------
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gt='git tag '
alias gc='git commit'
alias gd='git diff'
alias go='git checkout '
alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) \
    - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)'"
alias gla="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) \
    - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"


# ------------------------------------
#               macro
# ------------------------------------
function gfp () {
    echo "git fetch $1 && git remote prune $1"
    git fetch $1 && git remote prune $1
}
