#!/bin/bash
#!/bin/zsh
#
# ====================================
# Author: Eunchong Kim
# Date: Mar. 2021
# Project: user-settings
# Description: common
# ====================================

# Get shell type
shell_type=`ps -p$$ -ocmd=`

#-----------------------------------------------
#               Variables
#-----------------------------------------------
# Add .local to PATH
export PATH=~/.local/bin:$PATH

# Set default editor
export EDITOR='vim'

# Set nodename for vimrc to know if it is icepp or cern
export NODENAME=`uname -n | cut -f2 -d'.'`


#-----------------------------------------------
#               Source for WSL
#-----------------------------------------------
result=`cat /proc/version`
if [[ $result == *"icrosoft"* ]]; then # Include both 'microsoft' and 'Microsoft'
    source $HOME/user-settings/wsl
fi


#-----------------------------------------------
#               Source for ATLAS ICEPP/LXPLUS
#-----------------------------------------------
result=`uname -a`
if [[ $result == *"icepp"* ]] || [[ $result == *"lxplus"* ]]; then
    source $HOME/user-settings/atlas_common
fi

#-----------------------------------------------
#                   Alias
#-----------------------------------------------
# ls
alias ll='ls -l'

# Faster ssh X11 forwarding
alias ssh='ssh -XYC4 -c aes128-ctr'

# Git aliases
source $HOME/user-settings/git_aliases

# Grep exclude directory '.git'
alias grep='grep --exclude-dir=".git" --color'

# Python
alias py='time python3'


#-----------------------------------------------
#                   Macros
#-----------------------------------------------
# ROOT TBrowser
function rb() {
    root -l $1 -e "new TBrowser"
}


#-----------------------------------------------
#               Welcome message
#-----------------------------------------------
echo    "Hello, $USER! Today is $(date)."
#echo    "System Info: $(uptime)"
echo    " _______________________"
echo    "< You are on shell: $shell_type >"
echo -n " -----------------------"
cat <<< '
   \
    \
        .--.
       |o_o |
       |:_/ |
      //   \ \
     (|     | )
    / \_   _/\`\
    \___)=(___/
'
