#!/bin/bash
#!/bin/zsh
# profile_common
# ====================================
# Author: Eunchong Kim
# Date: Aug. 2021
# Project: user-settings
# Description: common
# ====================================


#-----------------------------------------------
#               Variables
#-----------------------------------------------
# add sbin
export PATH=$PATH:/usr/sbin:/sbin
# Add .local to PATH
export PATH=$PATH:~/.local/bin

# Set default editor
export EDITOR='vim'

# Set nodename for vimrc to know if it is icepp or cern
export NODENAME=`uname -n | cut -f2 -d'.'`


#-----------------------------------------------
#               Source for WSL
#-----------------------------------------------
result=`cat /proc/version`
if [[ $result == *"icrosoft"* ]]; then # Include both 'microsoft' and 'Microsoft'
    source $HOME/user-settings/wsl
fi


#-----------------------------------------------
#                   Alias
#-----------------------------------------------
# ls
alias ll='ls -l'

# Faster ssh X11 forwarding
alias ssh='ssh -XYC4 -c aes128-ctr'

# Git aliases
source $HOME/user-settings/git_aliases

# Grep exclude directory '.git'
alias grep='grep --exclude-dir=".git" --color'

# Python
alias py='time python3'

# Jupyter lab
alias jl='jupyter lab --no-browser'
alias prjl='poetry run jupyter lab --no-browser'
gprjl(){
    cd ~/workspace/poetry-env
    poetry run jupyter-lab --no-browser --notebook-dir=~ $@
}


#-----------------------------------------------
#                   npm
#-----------------------------------------------
export PATH="$HOME/.npm/bin:$PATH"


#-----------------------------------------------
#               Welcome message
#-----------------------------------------------
# Get shell type
shell_type=`ps -p$$ -ocmd=`
echo    "Hello, $USER! Today is $(date)."
#echo    "System Info: $(uptime)"
echo    " _______________________"
echo    "< You are on shell: $shell_type >"
echo -n " -----------------------"
cat <<< '
   \
    \
        .--.
       |o_o |
       |:_/ |
      //   \ \
     (|     | )
    / \_   _/\`\
    \___)=(___/
'
