#!/bin/bash
#!/bin/zsh
#
# ====================================
# Author: Eunchong Kim
# Date: Jan. 2021
# Project: user-settings
# Description: common setting for WSL
# ====================================


# ------------------------------------
#       Set X Server DISPLAY path
# ------------------------------------
export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0


# ------------------------------------
#   Start VcXsrv on Windows if not running
# ------------------------------------
# Get Windows running process list via powersell.exe and check if it is running
powershell.exe -Command '& tasklist' |
    if ! grep -q vcxsrv; then
        echo '[Warning] VcXsrv is not running. Starting the VcXSrv ...'
        powershell.exe -Command '& "C:\Program Files\VcXsrv\vcxsrv.exe" -multiwindow -nowgl -ac'
    fi
# Check again
powershell.exe -Command '& tasklist' |
    if ! grep -q vcxsrv; then
        echo '[Warning] VcXsrv is still not running! Check yourself.'
    else
        echo '[Info] VcXsrv is running.'
    fi

# Memo: VcXsrv Options
# -ac       disable access control restrictions
# -[no]wgl: Enable the GLX extension to use the native Windows WGL interface for hardware-accelerated OpenGL


# ------------------------------------
#               Alias
# ------------------------------------
# Change Directory
alias onedrive="cd /mnt/c/Users/eckim/OneDrive/workspace"
alias my-thesis='cd /mnt/c/Users/eckim/OneDrive/Docu/Work/JLAB/Master/thesis'
alias data='cd /mnt/d/data/'

# mkdir option
alias mkdir='mkdir -m 755'

# OPEN
alias open='xdg-open'

# Windows store apps
# Reference: https://www.tenforums.com/software-apps/57000-method-open-any-windows-10-apps-command-line.html
# WPS office
alias wpsoffice="powershell.exe -Command '& explorer.exe shell:AppsFolder\ZhuhaiKingsoftOfficeSoftw.WPSOffice2019_924xes6e8q1tw!WPSOffice2019'"
# TODO: add parameter of file to open

# Windows program
# Edge browser
export PATH=$PATH:/mnt/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application
alias edge='msedge.exe'


# ------------------------------------
#               Media
# ------------------------------------
# audio (may not work)
export PULSE_SERVER=tcp:localhost


# ------------------------------------
#       Windows terminal setting
# ------------------------------------
function wtsetting() {
    this_win_username=eunchong
    if [ -d "/mnt/c/Users/eckim" ]; then
        this_win_username=eckim
    fi
    setting_path=/mnt/c/Users/${this_win_username}/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
    vim $setting_path
    cp $setting_path $HOME/user-settings/windows-terminal/.
}


# ------------------------------------
#           Syncthing
# ------------------------------------
if [ -z "`pgrep syncthing`" ]; then # If syncthing is not running
    echo -e "[Warning] Syncthing is not running. Starting Syncthing ..."
    if [ -n "`syncthing -help 2>/dev/null`" ]; then # If synching -help is not empty
        syncthing -no-browser -logfile=".syncthing.log" -logflags="3" > /tmp/syncthing.out &
    fi
fi
# Check again
if [ -z "`pgrep syncthing`" ]; then # If syncthing is not running
    echo -e "[Warning] Syncthing is still not running! Check yourself."
else
    echo -e "[Info] Syncthing is running."
fi
